spring.datasource.url=jdbc:postgresql://ep-gentle-smoke-ag2d09ne.c-2.eu-central-1.pg.koyeb.app/koyebdb
spring.datasource.username=koyeb-adm
spring.datasource.password=npg_SV3BN7LqXdQc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true